<<<<<<< HEAD
branches:
  only:
    - master

=======

branches:
  only:
    - master
    
>>>>>>> master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16"

addons:
  firefox: "17.0"
  
language: python

python:
  - "3.3"

install: 
  - pip install -r requirements.txt

script: 
  - python manage.py test -v 2
